### ISSUE TITLE
Roadmap for LotkaVolterra.jl

### ISSUE THREAD

**Issue by gajomi** [gajomi/LotkaVolterra.jl#2]
This issue outlines a roadmap leading to a production version of the LotkaVolterra package. The goals of this package can be separated into three different kinds of functionality
- providing container types to parameterize different kinds of Lotka-Volterra systems
- providing high performance simulation of initial value problems for Lotka-Volterra systems
- analysis of features of different kinds of Lotka-Volterra systems

Within each of these issues there is the need to establish a an api for the basic types and methods.

Associated with these three general kinds of functionality are a number of specific targets that advance the cause of the package
1. Standard Lotka-Volterra predator prey type
   - [x] define type in terms of standard parameters and basic methods
   - [ ] symplectic integration of trajectories 
   - [ ] qualitative behavior methods 
   - [ ] cycle family type (container type for cycles; seems to be needed)
2. Generalized Lotka-Volterra type
   - [x] define type in terms of standard parameters and basic methods
   - [ ] qualitative behavior methods (existence/values of fixed points, cycles and their stabilities)
   - [ ] example implementation of parameterized types, like food webs or food chains
3. Generalized Lotka-Volterra predator prey type
   - [ ] define type in terms of standard parameters and basic methods
   - [ ] implementation of qualitative behavior functions
4. Specialized numerical integration functions
5. Stabilization of the extent of the api for analysis of feature of dynamical systems in the LV context
